/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testOneQuotes(){
        Quote quote = new Quote(new String[]{"rare"},"sanabel","8 likes","be you");
        assertNotNull(quote);
    }
    @Test void testMultipleQuotes(){
        Quote quote = new Quote(new String[]{"rare"},"sanabel","8 likes","be you");
        Quote quote1 = new Quote(new String[]{"busy"},"life","10 likes","prove your self");
        Quote quote2 = new Quote(new String[]{"rare"},"sanabel","8 likes","be you");
        assertNotNull(quote);
        assertNotNull(quote1);
        assertNotNull(quote2);
    }
    // make this test with to method
    @Test void testEmptyQuotes(){
        Quote quote = new Quote(new String[]{""},"","","");
        assertNotNull(quote);
    }
   // try test by using the Assertions
   @Test void testEmptyQuotes2(){
       Quote quote = new Quote(new String[]{""},"","","");
       Assertions(quote);
   }

    private void Assertions(Quote quote) {
    }
}
