/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void testOneQuotes(){

    }
    @Test void testMultipleQuotes(){

    }
    // make this test with to method
    @Test void testEmptyQuotes(){

    }
   // try test by using the Assertions
   @Test void testEmptyQuotes2(){
     
   }

    private void Assertions(Quote quote) {
    }
}
