/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.lang.Math;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        Path path = Paths.get("app/src/main/resources/recentquotes.json");

        BufferedReader reader = null;
        try {
            Gson gson = new Gson();
            reader = new BufferedReader(new FileReader(String.valueOf(path)));
//            new TypeToken<ArrayList<Quote>>(){}.getType();
            ArrayList<Quote> quote = new Gson().fromJson(reader , new TypeToken<ArrayList<Quote>>(){}.getType());
            int randomQuete = (int) (Math.random()*quote.size());
            System.out.println(randomQuete);
            System.out.println(quote.get(randomQuete));
            reader.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
